### ISSUE TITLE
Add a janitor / way to clean up images

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#117]
There is a risk in leaving "old" images around too long. We should evaluate having a "janitor" to clean up old and defunct images

**Comment by colearendt** [comment]
A downside here - it is nice having old versions around so that we can easily test old product versions when customers are running into issues in old environments 🤷‍♂️

**Comment by ianpittwood** [comment]
I want to take this one on after I close out a couple other tickets. Docker Hub's [Advanced Image Management API](https://docs.docker.com/docker-hub/api/latest/#tag/images) seems like a decent way to do this, but we'll want to decide what criteria we want to prune on:

* Prune based off image age (i.e. image was pushed >2yrs ago then we can prune it).
* Prune based off last active time, the time since the image was last pushed or pulled. This is supported directly by the API with a default of 1 month.
* Some mix of the two.

We could also consider pruning any "preview" images at a faster clip than other images or even separating them into another feed (i.e. rstudio/workbench-preview) to make the distinction clearer for end users and so we can more easily apply different sets of rules to them. 

I'm leaning towards pruning based on last active time, but maybe at a further out timeline like 6 months to a year.
