### ISSUE TITLE
Tagging source code for extending images with versioning

### ISSUE THREAD

**Issue by darrenmedwards** [rstudio/rstudio-docker-products#123]
I'm trying to build a pipeline that extends these rsp and rsc images. However, I have to build from source since I need to use a custom Ubuntu OS layer (instead of rstudio/r-base). I was hoping to pull from tagged versions of the source (instead of master) so that my pipeline can maintain version re-producibility. Do you have any plans to add source code tagging in your git hooks? Or do you think there is some better way I can extended these base images and maintain source versioning?

**Comment by colearendt** [comment]
Thanks so much for reaching out here @darrenmedwards !! Do you mind my asking exactly what type of tagged versions you imagine?

Unfortunately just tagging the first build of the product at a particular version may not match the "last" way that we build that image, and updating the tag would not help at all for reproducibility of the source 😞 

(i.e. when RSC first updates to 1.8.8.2, we will build it here. However, we may improve the Dockerfile or make changes to the code here before the next release of RSC lands. How would you expect tagging to work in that case?)

For instance, one way we could tag is just at the start of every month, create a 202101 tag, 202102 tag, etc. But that is also not super helpful since it will not necessarily correlate to the images. Does it work for you to pin to certain commits? Just whenever you pull / update the source, save the commit that you are referencing?

I'm not sure I am 100% understanding your use case, so am hopeful that discussing a bit more will help me understand 😄

**Comment by darrenmedwards** [comment]
For my purposes, I think it would be sufficient if the source code could be tagged with the same image tag and maybe some additional, immutable qualifier. I wouldn't need tags for non-release code

I think the image tags map to the RStudio product version and uses _major.minor.patch-qualifier_ convention. Maybe the image build source code can be tagged with _major.minor.patch-qualifier-unique_build_id_ (or maybe an incremental build #). So for example, the image tag [1.4.1106-5](https://hub.docker.com/layers/rstudio/rstudio-server-pro/1.4.1106-5/images/sha256-51b29696ec293ffb9634eb2ce8450f32dc1af2dbf4b72b09d9e0363fd5b7cbb5?context=explore) could be built from git code tags 1.4.1106-5-1, 1.4.1106-5-2, and 1.4.1106-5-3

For my use case, this would allow me to create my own build pipeline that (1) pulls a tagged version of rstudio-docker-products, (2) performs a few regex find/replace on the Dockfile or other files, and (3) runs the docker build within my docker build environment. Also, with this methodology, I wouldn't have to fork the code that could potentially lead to drift. For better supportability purposes, this would allow me to stay tightly coupled with rstudio-docker-products... if that's ok 😄

Your idea to pin commits might work too, but I would just want to be sure the commit I'm using is stable and ideally tied to a released image tag. 

Thanks for your engagement @colearendt!

**Comment by colearendt** [comment]
Whew! Two weeks has passed already!? I thought I responded to this 🙈 Sorry about that!

Thanks for your patience! I like this idea / pattern a lot! Plus it could help us keep track of things in the repository a bit easier as well.

We are currently in the process of refactoring some of our repositories / CI processes. I suspect ultimately this type of incremental build # will probably be best implemented in CI. Unfortunately it may take us a little while to get this rolling properly, but I am definitely hopeful that we can craft a good solution here!

**Comment by colearendt** [comment]
We now publish docker images that have a SHA associated with them. The SHA is the `git` SHA of the code that produced them. Hopefully that is sufficient to accomplish this task! We do not have tagged releases (yet), but builds can be tracked against source code in this way.

**Comment by colearendt** [comment]
Also, it's worth noting that we are nearing a state where not every git commit will build every image. We are hoping to only build images that "changed" / need to be built. So the workflow you describe where you start from a released image is still probably the best strategy in this case 😄 

#255
