### ISSUE TITLE
How to create single custom rstudio connect Dockerfile

### ISSUE THREAD

**Issue by devivaraprasad901** [rstudio/rstudio-docker-products#141]
Hi All,

I want to run shinyapp in rstudio connect and finally need to deploy in Kubernetes. For that I am writing single Dockerfile, but unable to process the same.

I have seen your repo for RstudioConnect having two dockerfiles(Connect and Connect-content-init) and I tried to merged in single docker of Connect folder and build the same with docker compose yaml file but Image is not working.

Could you please share some single Dockerfile for Rstudio Connect to host shinyapp application.

**Comment by colearendt** [comment]
It sounds to me like this would be a discussion that would be more effective to have over the phone / a virtual call. Do you mind reaching out to your Customer Success representative so that we can set up a call with our Solutions Engineering team?

We can come back here to update the issue once we have made sure that we're all on the same page 😄 If you don't have a go-to contact at RStudio, you can reach out to sales@rstudio.com for us to direct to the appropriate person 😄

**Comment by colearendt** [comment]
Closing this as I believe there is a bit of confusion. Please reach out if you have more questions! It sounds like this may be a conversation that is better to have on RStudio Community or a dedicated phone call 😄
