### ISSUE TITLE
Add Instructions for Using a License Server

### ISSUE THREAD

**Issue by nicholsn** [rstudio/rstudio-docker-products#27]
Is it currently possible to connect to a license server rather than passing a `License Key`? If so, it would be great if the instructions could be added to the readme.

Also, not sure if this would make sense, but it might be useful to have a docker image added here that could be used to run the license server.

**Comment by colearendt** [comment]
Thanks for commenting here! That is a fantastic point - we definitely should document that! 

Regarding running a docker image for running the license server - we generally recommend against that practice since any "reboot" of the container could cause trouble for all of your licensing. We will think through this a bit more though 😄Do you run the license server in a container today?

**Comment by nicholsn** [comment]
Thanks and I see, that makes sense why you wouldn't run the license server in docker. Our license server is running as a standalone server. Appreciate the offer to add docs!
