### ISSUE TITLE
How to verify status of services

### ISSUE THREAD

**Issue by darrenmedwards** [rstudio/rstudio-docker-products#318]
The status command does not appear to be available. What is the best way to verify that rstudio and launcher services has successfully started? I'm trying to find a command that I can put into a test stage of my container build pipeline. Thanks
![image](https://user-images.githubusercontent.com/42631497/170083107-89e3acc0-b25d-4e70-8b74-69ab4f2818d0.png)

**Comment by colearendt** [comment]
Hello! This is a fantastic question! Unfortunately these checks are not working because those shell scripts depend on `systemd`, which does not exist in our containers. Some ideas:

- from our test pipeline, can check for the ports to be listening:
https://github.com/rstudio/rstudio-docker-products/blob/1d1b5fe9bf2bf71da6f6c45ef40ffc33cbb5cba7/workbench/test/goss.yaml#L16-L26
- or can check for the processes to be running:
https://github.com/rstudio/rstudio-docker-products/blob/1d1b5fe9bf2bf71da6f6c45ef40ffc33cbb5cba7/workbench/test/goss.yaml#L28-L34
- another idea is to use the health checks for the service: 
    - http://localhost:8787/health-check for rstudio-server executable
    - http://localhost:5559/status for rstudio-launcher

Ultimately some of these checks unfortunately depend on a license being available (which we have done in our tests), although you could probably discern "license errors" vs. other errors in some cases as well (i.e. the health check returns a dedicated status code for license issues).

Ultimately we hope to improve this type of usability / observability of the service and its health - does that help answer your question?

**Comment by darrenmedwards** [comment]
This is perfect. Thanks, Cole!
