### ISSUE TITLE
missing Dockerfile for ubuntu 20.04(focal) 

### ISSUE THREAD

**Issue by TheBerberiCode** [rstudio/rstudio-docker-products#484]
Hi,

I've noticed the Dockerfile for ubuntu 20.04 is missing but the dockerfile for bionic and jammy does exist. Is this by design and we shouldn't use focal in our  posit connect container images? Thank you!

**Comment by colearendt** [comment]
Howdy! This is a fantastic question. You are welcome to use focal if you prefer! We mostly skipped focal because we did not end up adding a secondary ubuntu image until jammy was out. As a result, focal was a bit overkill for our "publicly built / maintained" images.

Basically, no reason not to use focal 😄 We just opted not to out of convenience. At this point, it is unlikely we will decide to add a publicly maintained focal image - much more likely that we will evaluate adding a RHEL type of system, as discussed here: #305

**Comment by TheBerberiCode** [comment]
@colearendt  thank you for clearing this up!!
