### ISSUE TITLE
Basic validation testing for GCP Cloud Workstations image

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#490]
We'll need to setup regression testing on the Cloud Workstations image (#459) to ensure that when we push updates it won't interrupt customers running on Cloud Workstations.

Adding Goss tests, similar to the other Docker images, should provide a good baseline to ensure we're releasing working images to customers. Goss tests should be completed and working prior to general release.

**Comment by bdeitte** [comment]
Stil needs to be split into two tickets, and James is also going to talk to Google about what they will be doing here.

**Comment by bdeitte** [comment]
@ianpittwood Can we split half of this off into another ticket?  I assume you are tackling the goss part now?

**Comment by ianpittwood** [comment]
@bdeitte Yeah, I think it would make sense to split it up.

**Comment by ianpittwood** [comment]
Basic Goss tests found in the standard Workbench image have been implemented, but I'd like to explore any other tests we may want to run before calling this "Done". Some things that spring to mind for validation checks:
* Check that token auth is disabled for JupyterLab (fix for #517)
* Check that Jupyter Shell is set to `/bin/bash` instead of `/bin/sh`
* Check that package lists in `deps/` are installed to each installed version of R and Python
* Check that Workbench is properly configured to bypass signin and always use default account, `user`

**Comment by ianpittwood** [comment]
Goss tests added to cover everything I could think of for now.
