### ISSUE TITLE
Figure out what we want to do around "LTS"

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#64]
The biggest problem here is for RStudio Connect. If we change R / Python versions, users who are using the image stand to experience all of their content breaking at once.

We should think through how to make that switch. Should we be providing an image that will only do _additive_ R / Python version additions for "LTS"? At least for very long periods of time? Will product changes make this easier? Actual user feedback preferred 😄

**Comment by danielfrg** [comment]
It's a good point, I would prefer to keep just one docker image.

I think what we do is what you mentioned additive installs of the runtimes while also removing old (2 versions old or a specific timeline), thinking about what most languages do i think python supports only 3 minor versions at a time and with each new one they deprecate another. This usually give people a lot of time since they release around twice a year.

**Comment by colearendt** [comment]
100%. That's a great call. One concern that will go along with this is image size. The images will get progressively larger 😛 

IMO we should figure out a standard, publicize it / document it, and then give a bit of burn in to implement. People will have time, but they will potentially eat updates without realizing when they upgrade. We could also coordinate "breaking" releases with "major" releases of product versions 🤷‍♂️

**Comment by danielfrg** [comment]
You know I dont care much about size 🙈 

> but they will potentially eat updates without realizing when they upgrade

Agree but this happens with everything so I am not very worried about making this perfect, just good enough and standard.

> We could also coordinate "breaking" releases with "major" releases of product versions 🤷‍♂️

That could work but it might make more sense to "break it" when the runtimes stop supporting to keep it more in sync with the actual sorce.

**Comment by colearendt** [comment]
Support of the containers is tied to product support
