### ISSUE TITLE
Provide tags that point to latest version of base image

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio-docker-products#67]
Customer request from internal ticketing system, ticket 51638:

> Regarding tags - one of tags we had in conf file was removed (rstudio/r-session-complete:centos7-1.3.842-1) and made confusion among our users.
> Therefor I would suggest to use some tags like centos7-latest or similar that would always point to latest version for specific base image.

**Comment by colearendt** [comment]
This belongs in https://github.com/rstudio/docker-r-session-complete . In particular, we have been reluctant in the past to add a `latest` image for the "preview" images since it is "bad practice" and leads to not-reproducible behavior in many cases.

As a concession here, we added a "preview" suffix for image tags that will potentially get removed as a visual indicator of what image versions are reliably usable, etc.

**Comment by colearendt** [comment]
This is addressed now in that we only share public / released builds in our main repos
